name: Runs every 20 minutes

on:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  build:
    name: Run every 20 minutes
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo Hello World
